services:
  note-server:
    build:
      context: ./note-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      # Mount home directory to persist configuration
      - ~/.noteai:/home/app/.noteai
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 2s
      retries: 3
    networks:
      - note-network

  note-web:
    build:
      context: ./note-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NOTE_SERVER_URL=http://note-server:8080
    depends_on:
      note-server:
        condition: service_healthy
    networks:
      - note-network

networks:
  note-network:
    driver: bridge
