name: Test Server
# This workflow tests the Go server application

on:
  push:
    branches: [ master, main ]
    paths:
      - 'note-server/**'
      - '.github/workflows/test-server.yml'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'note-server/**'
      - '.github/workflows/test-server.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Download dependencies
      working-directory: note-server
      run: go mod download

    - name: Verify dependencies
      working-directory: note-server
      run: go mod verify

    - name: Verify FFmpeg installation
      run: |
        ffmpeg -version
        ffprobe -version

    - name: Build application
      working-directory: note-server
      run: go build ./...

    - name: Run tests with coverage
      working-directory: note-server
      run: go test -v -coverprofile=coverage.out ./...

    - name: Generate coverage report
      working-directory: note-server
      run: go tool cover -html=coverage.out -o coverage.html

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: server-coverage-report
        path: note-server/coverage.html
        retention-days: 30

