name: Test CLI
# This workflow tests the Go CLI application

on:
  push:
    branches: [ master, main ]
    paths:
      - 'note-cli/**'
      - '.github/workflows/test-cli.yml'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'note-cli/**'
      - '.github/workflows/test-cli.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg build-essential
        
    - name: Download dependencies
      working-directory: note-cli
      run: go mod download
      
    - name: Verify dependencies
      working-directory: note-cli
      run: go mod verify
      
    - name: Verify FFmpeg installation
      run: |
        ffmpeg -version
        ffprobe -version
        
    - name: Build application
      working-directory: note-cli
      run: go build -o note cmd/note/main.go
      
    - name: Set environment variables
      run: |
        echo "CGO_ENABLED=1" >> $GITHUB_ENV
        echo "HOME=/home/runner" >> $GITHUB_ENV
        
    - name: Setup test environment
      run: |
        mkdir -p /home/runner/.noteai
        mkdir -p /home/runner/.noteai/.cache
        mkdir -p /home/runner/.noteai/notes
        mkdir -p /home/runner/.noteai/meetings
        mkdir -p /home/runner/.noteai/interviews
        mkdir -p /home/runner/.noteai/recordings
        chmod -R 755 /home/runner/.noteai
        
    - name: Debug environment
      run: |
        echo "Go version:"
        go version
        echo "Go environment:"
        go env
        echo "FFmpeg version:"
        ffmpeg -version | head -5
        echo "Current user and home:"
        whoami
        echo $HOME
        ls -la $HOME/.noteai/ || echo "No .noteai directory yet"
        
    - name: Run tests
      working-directory: note-cli
      run: go test -v -timeout 5m ./...
      
    - name: Run tests with coverage
      working-directory: note-cli
      run: go test -v -coverprofile=coverage.out ./...
      
    - name: Generate coverage report
      working-directory: note-cli
      run: go tool cover -html=coverage.out -o coverage.html
      
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: cli-coverage-report
        path: note-cli/coverage.html
        retention-days: 30
