name: Test CLI
# This workflow tests the Go CLI application

on:
  push:
    branches: [ master, main ]
    paths:
      - 'note-cli/**'
      - '.github/workflows/test-cli.yml'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'note-cli/**'
      - '.github/workflows/test-cli.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Change to CLI directory
      run: cd note-cli
      
    - name: Download dependencies
      run: cd note-cli && go mod download
      
    - name: Verify dependencies
      run: cd note-cli && go mod verify
      
    - name: Run tests
      run: cd note-cli && go test -v ./...
      
    - name: Run tests with coverage
      run: cd note-cli && go test -v -coverprofile=coverage.out ./...
      
    - name: Generate coverage report
      run: cd note-cli && go tool cover -html=coverage.out -o coverage.html
      
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: cli-coverage-report
        path: note-cli/coverage.html
